# Generated by Django 5.0.3 on 2024-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_image_property_landlord_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(default="path/to/default/image.jpg", upload_to=""),
        ),
    ]
